[project]
dependencies = [
  "openpyxl>=3.1.5",
  "pydantic>=2.12.5",
  "requests>=2.32.5",
  "rich>=14.3.3",
]
description = "Add your description here"
name = "extract"
readme = "README.md"
requires-python = ">=3.14.3"
version = "0.1.0"

[tool.ruff]
src = ["src"]

[tool.ruff.lint]
select = ["F401"] # F401 = unused imports

[dependency-groups]
dev = [
  "ruff>=0.15.4",
]
